[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "workday-calendar"
version = "0.1.0"
description = "Calculate a datetime a number of workdays from a starting point."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["."]
python_files = ["*_test.py", "test_*.py"]

[tool.coverage.run]
omit = ["*_test.py"]
